[package]
name = "ide_completion"
version = "0.0.0"
edition = "2021"

[dependencies]
base_db = { path = "../base_db" }
hir = { path = "../hir" }
hir_ty = { path = "../hir_ty" }
hir_def = { path = "../hir_def" }
syntax = { path = "../syntax" }
always-assert = { version = "0.2", features = ["tracing"] }
tracing = { workspace = true }

text-edit = { workspace = true }
itertools = "0.12"
either = { workspace = true }
rowan = { workspace = true }
